spring:
  cloud:
    config:
      override-none: true #本地配置文件覆盖服务器上的文件
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    pool:
      max-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: 60000
      database: 0
      timeout: 60000
  messages:
    basename: i18n/messages,i18n/domain #多语言翻译
  http:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
  rabbitmq:
    host: 127.0.0.1
    username: rabbitmq
    password: Ab123456
    port: 5672
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 100 #最大活跃数
    initialSize: 1 #初始化数量
    maxWait: 60000 #最大连接等待超时时间
    poolPreparedStatements: true #打开PSCache，并且指定每个连接PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    minIdle: 6
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat, wall, log4j #配置监控统计拦截的filters，去掉后监控界面sql将无法统计 ,'wall'用于防火墙
  jpa:
    properties:
      hibernate:
        format_sql: true
        database: MYSQL
        show-sql: false
        dialect: com.domain.common.MySQLDialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@127.0.0.1:8009/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    appname: ${spring.application.name}${instance.suffix:}
    virtualHostName: ${spring.application.name}${instance.suffix:}
    secureVirtualHostName: ${spring.application.name}${instance.suffix:}
    
#全局变量
mongodb_uri: mongodb://127.0.0.1:20000,127.0.0.1:20001
datasource_url: jdbc:mysql://127.0.0.1:3306
