spring:
  datasource:
    url: ${datasource_url}/sos?useUnicode=true&characterEncoding=utf-8&useSSL=false
  sleuth:
    enabled: false #表示当前程序不使用sleuth
  cloud:
    stream:
      bindings:
        sleuth:
          consumer:
            concurrency: 4
  elasticsearch:
    bboss:
      elasticUser: ${zipkin.storage.elasticsearch.username}
      elasticPassword: ${zipkin.storage.elasticsearch.password}
      elasticsearch:
        index: optlog-65
        rest:
          hostNames: ${zipkin.storage.elasticsearch.hosts}
        dateFormat: yyyy-MM-dd
        timeZone: Asia/Shanghai
        ttl: 2d
        discoverHost: true #客户端动态发现es集群节点控制开关
      dslfile:
        refreshInterval: -1 # dsl配置文件热加载扫描时间间隔，毫秒为单位，默认5秒扫描一次，<= 0时关闭扫描机制
      #http链接池配置
      http:
         timeoutConnection: 400000
         timeoutSocket: 400000
         connectionRequestTimeout: 400000
         retryTime: 1
         maxLineLength: -1
         maxHeaderCount: 200
         maxTotal: 400
         defaultMaxPerRoute: 200
         soReuseAddress: false
         soKeepAlive: false
         timeToLive: 3600000
         keepAlive: 3600000
         keystore:
         keyPassword:
         hostnameVerifier:
zipkin:
  storage:
    type: elasticsearch #表示zipkin数据存储方式是elasticsearch
    elasticsearch:
      hosts: 127.0.0.1:9200
      max-requests: 64
      index: zipkin
      index-shards: 5
      index-replicas: 0
      username: zipkin
      password: zipkin1101
    